# Generated by Django 6.0.4 on 2026-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_kitsizeoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="external_client_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
