# Generated by Django 6.0.4 on 2026-06-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationcode_code_hash"),
        ("members", "0003_guardian_external_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="parent_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardian",
                to="accounts.parentaccount",
            ),
        ),
    ]
