# Generated by Django 6.0.4 on 2026-06-15 08:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_guardian_parent_account"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="traininggroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="uniq_training_group_name_ci",
            ),
        ),
    ]
