# Generated by Django 6.0.4 on 2026-06-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationcode_code_hash"),
        ("members", "0006_consolidate_guardians"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guardian",
            name="email",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="phone",
        ),
        migrations.AlterField(
            model_name="guardian",
            name="parent_account",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardian",
                to="accounts.parentaccount",
            ),
        ),
    ]
