# Generated by Django 6.0.4 on 2026-06-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_remove_guardian_email_remove_guardian_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardian",
            options={"verbose_name": "Vecāks", "verbose_name_plural": "Vecāki"},
        ),
    ]
