# Generated by Django 6.0.4 on 2026-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_guardian_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="discontinuation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="member",
            name="discontinued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="discontinued_effective_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[("active", "Aktīvs"), ("discontinued", "Pārtraukts")],
                default="active",
                max_length=16,
            ),
        ),
    ]
