# Generated by Django 6.0.4 on 2026-07-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_guardian_name_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guardian",
            name="full_name",
        ),
    ]
