# Generated by Django 6.0.4 on 2026-08-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_remove_guardian_full_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("column_keys", models.JSONField()),
                (
                    "agreement_status_filters",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_export_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="export_templates",
                        to="members.traininggroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
    ]
