# Generated by Django 6.0.4 on 2026-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclinktoken",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
