# Generated by Django 6.0.4 on 2026-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationcode_code_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="origin_session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
