# Generated by Django 6.0.4 on 2026-05-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0002_kitsizeoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("generated", "Sagatavots"),
                            ("sent", "Nosūtīts parakstīšanai"),
                            ("signed", "Parakstīts"),
                            ("void", "Atcelts"),
                        ],
                        default="generated",
                        max_length=16,
                    ),
                ),
                (
                    "signing_path",
                    models.CharField(
                        choices=[
                            ("electronic", "Elektroniski"),
                            ("paper", "Ar roku, papīra dokuments"),
                        ],
                        default="electronic",
                        max_length=16,
                    ),
                ),
                ("generated_at", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True, default="")),
                (
                    "external_provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "external_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("external_url", models.URLField(blank=True, default="")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("member",),
                        name="one_current_agreement_per_member",
                    )
                ],
            },
        ),
    ]
