# Generated by Django 6.0.4 on 2026-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0002_backfill_agreements_for_approved_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="external_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
