# Generated by Django 6.0.4 on 2026-06-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0003_agreement_external_error_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="state",
            field=models.CharField(
                choices=[
                    ("generated", "Sagatavots"),
                    ("sent", "Nosūtīts parakstīšanai"),
                    ("signed", "Parakstīts"),
                    ("void", "Atcelts"),
                    ("superseded", "Aizvietots"),
                    ("discontinued", "Pārtraukts"),
                ],
                default="generated",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AgreementLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("minor_amendment", "Neliels labojums"),
                            (
                                "material_amendment_started",
                                "Sākta būtiska izmaiņu procedūra",
                            ),
                            ("superseded", "Aizvietots ar jaunu līgumu"),
                            ("discontinued", "Dalība pārtraukta"),
                            ("credit_note_created", "Izveidots kredītrēķins"),
                            ("credit_note_applied", "Kredīts piemērots rēķinam"),
                            ("credit_note_failed", "Kredītrēķina izveide neizdevās"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="agreements.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
