# Generated by Django 6.0.4 on 2026-07-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0004_p8_lifecycle"),
        ("billing", "0012_billingrecord_first_billing_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="billing_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="billing.membershipplan",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="first_billing_month",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
    ]
