# Generated by Django 6.0.4 on 2026-09-03 04:31

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0006_agreement_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact",
            field=models.FileField(
                blank=True,
                default="",
                max_length=255,
                storage=apps.documents.storage.PrivateDocumentStorage(),
                upload_to="agreements/signed/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact_content_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact_file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact_original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_artifact_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
