# Generated by Django 6.0.4 on 2026-06-07 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("season", models.CharField(max_length=16)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "annual_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("300.00"), max_digits=8
                    ),
                ),
                (
                    "sibling_discount_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("installment_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "first_installment_month",
                    models.PositiveSmallIntegerField(default=9),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
