# Generated by Django 6.0.4 on 2026-06-07 07:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0003_agreement_external_error_code"),
        ("billing", "0001_initial"),
        ("members", "0002_kitsizeoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season", models.CharField(max_length=16)),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_full_price", models.BooleanField(default=True)),
                (
                    "sibling_discount_percent_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("upfront", "Vienā maksājumā"),
                            ("installments", "Pa daļām"),
                        ],
                        default="installments",
                        max_length=16,
                    ),
                ),
                ("full_price_opt_out", models.BooleanField(default=False)),
                (
                    "manual_amount_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("manual_override_reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Sagatavots"),
                            ("confirmed", "Apstiprināts"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_records",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_records",
                        to="members.member",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_records",
                        to="billing.membershipplan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "season"),
                        name="one_billing_record_per_member_per_season",
                    )
                ],
            },
        ),
    ]
