# Generated by Django 6.0.4 on 2026-06-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_billingrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="external_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="external_status",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="external_product_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "external_invoice_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "external_status",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "external_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="billing.billingrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("billing_record", "sequence"),
                        name="one_invoice_per_record_sequence",
                    )
                ],
            },
        ),
    ]
