# Generated by Django 6.0.4 on 2026-06-08 13:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_billingrecord_external_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginvoice",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="paid_to_date",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpaid", "Nav apmaksāts"),
                    ("partial", "Daļēji apmaksāts"),
                    ("paid", "Apmaksāts"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpaid", "Nav apmaksāts"),
                    ("partial", "Daļēji apmaksāts"),
                    ("paid", "Apmaksāts"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="payment_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
