# Generated by Django 6.0.4 on 2026-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_billing_payment_sync_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="payment_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
