# Generated by Django 6.0.4 on 2026-06-09 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_billingrecord_payment_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipplan",
            name="payment_due_day",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Mēneša diena, kad iestājas maksājuma termiņš (1–31).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="skip_months",
            field=models.CharField(
                blank=True,
                default="7,12",
                help_text='Mēneši (1–12) bez rēķina, ar komatu, piem. "7,12" (jūlijs, decembris).',
                max_length=32,
            ),
        ),
    ]
