# Generated by Django 6.0.4 on 2026-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_membershipplan_schedule_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginvoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
