# Generated by Django 6.0.4 on 2026-06-30 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0004_p8_lifecycle"),
        ("billing", "0009_billing_send_due_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginvoice",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BillingAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("credit_note", "Kredītrēķins")], max_length=16
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "external_credit_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "external_status",
                    models.CharField(blank=True, default="pending", max_length=16),
                ),
                (
                    "external_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "applied_to_external_invoice_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("requires_staff_apply", models.BooleanField(default=False)),
                (
                    "agreement_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="agreements.agreementlifecycleevent",
                    ),
                ),
                (
                    "billing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="billing.billingrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_adjustments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="billing.billinginvoice",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
