# Generated by Django 6.0.4 on 2026-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_p8_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginvoice",
            name="external_cancellation_action",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="external_cancellation_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="billinginvoice",
            name="external_cancellation_status",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
