# Generated by Django 6.0.4 on 2026-07-03 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_billinginvoice_external_cancellation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="first_billing_month",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="billing_start_cutoff_day",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Mēneša diena, līdz kurai pirmais rēķina mēnesis ir tekošais mēnesis.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="membershipplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="one_default_membership_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_default", False), ("is_active", True), _connector="OR"
                ),
                name="default_membership_plan_must_be_active",
            ),
        ),
    ]
