# Generated by Django 6.0.4 on 2026-07-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billinginvoice_external_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipplan",
            name="sibling_discount_percent",
        ),
    ]
