# Generated by Django 6.0.4 on 2026-06-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="AddressImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("region_codes", models.TextField(blank=True)),
                ("group_count", models.PositiveIntegerField(default=0)),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AddressGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("normalized_label", models.CharField(db_index=True, max_length=255)),
                ("street_code", models.CharField(blank=True, max_length=32)),
                ("street_name", models.CharField(blank=True, max_length=255)),
                ("locality_code", models.CharField(blank=True, max_length=32)),
                ("locality_name", models.CharField(blank=True, max_length=255)),
                (
                    "region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("region_name", models.CharField(blank=True, max_length=255)),
                ("entry_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["street_code"], name="addresses_a_street__ec369c_idx"
                    ),
                    models.Index(
                        fields=["region_code", "locality_code"],
                        name="addresses_a_region__776676_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AddressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vzd_code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("normalized_label", models.CharField(db_index=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=16)),
                (
                    "region_code",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("region_name", models.CharField(blank=True, max_length=255)),
                ("koord_x", models.CharField(blank=True, max_length=32)),
                ("koord_y", models.CharField(blank=True, max_length=32)),
                ("dd_n", models.CharField(blank=True, max_length=32)),
                ("dd_e", models.CharField(blank=True, max_length=32)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="addresses.addressgroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["normalized_label"],
                        name="addresses_a_normali_44fdef_idx",
                    ),
                    models.Index(
                        fields=["group", "normalized_label"],
                        name="addresses_a_group_i_25cf15_idx",
                    ),
                    models.Index(
                        fields=["region_code"], name="addresses_a_region__0ec7ae_idx"
                    ),
                ],
            },
        ),
    ]
