# Generated by Django 6.0.4 on 2026-06-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressApartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vzd_code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("normalized_label", models.CharField(db_index=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=16)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="addresses.addressentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["building", "normalized_label"],
                        name="addresses_a_buildin_5d2692_idx",
                    ),
                    models.Index(
                        fields=["normalized_label"],
                        name="addresses_a_normali_01c0e4_idx",
                    ),
                ],
            },
        ),
    ]
