# Generated by Django 6.0.4 on 2026-06-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("application_approved", "Application approved"),
                            ("application_rejected", "Application rejected"),
                            ("application_fix_requested", "Application fix requested"),
                            ("training_group_assigned", "Training group assigned"),
                            ("training_group_cleared", "Training group cleared"),
                            ("document_previewed", "Document previewed"),
                            ("document_downloaded", "Document downloaded"),
                            ("document_deleted", "Document deleted"),
                            ("agreement_sent", "Agreement sent"),
                            ("agreement_signed", "Agreement signed"),
                            ("agreement_voided", "Agreement voided"),
                            ("agreement_sync_failed", "Agreement sync failed"),
                            ("billing_push_triggered", "Billing push triggered"),
                            ("payment_sync_triggered", "Payment sync triggered"),
                            ("invoice_push_failed", "Invoice push failed"),
                            ("invoice_send_failed", "Invoice send failed"),
                            ("payment_sync_failed", "Payment sync failed"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="core_audite_target__8673ce_idx",
                    ),
                    models.Index(
                        fields=["action"], name="core_audite_action_9297cd_idx"
                    ),
                ],
            },
        ),
    ]
