# Generated by Django 6.0.4 on 2026-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("application_approved", "Application approved"),
                    ("application_rejected", "Application rejected"),
                    ("application_fix_requested", "Application fix requested"),
                    ("training_group_assigned", "Training group assigned"),
                    ("training_group_cleared", "Training group cleared"),
                    ("document_previewed", "Document previewed"),
                    ("document_downloaded", "Document downloaded"),
                    ("document_deleted", "Document deleted"),
                    ("agreement_sent", "Agreement sent"),
                    ("agreement_signed", "Agreement signed"),
                    ("agreement_voided", "Agreement voided"),
                    ("agreement_sync_failed", "Agreement sync failed"),
                    ("billing_push_triggered", "Billing push triggered"),
                    ("payment_sync_triggered", "Payment sync triggered"),
                    ("invoice_push_failed", "Invoice push failed"),
                    ("invoice_send_failed", "Invoice send failed"),
                    ("payment_sync_failed", "Payment sync failed"),
                    ("data_exported", "Data exported"),
                    ("billing_record_confirmed", "Billing record confirmed"),
                    ("training_groups_merged", "Training groups merged"),
                    ("agreement_minor_amended", "Agreement minor amended"),
                    (
                        "agreement_material_amendment_started",
                        "Agreement material amendment started",
                    ),
                    ("agreement_superseded", "Agreement superseded"),
                    ("member_discontinued", "Member discontinued"),
                    ("billing_credit_created", "Billing credit created"),
                    ("billing_credit_failed", "Billing credit failed"),
                    ("billing_credit_applied", "Billing credit applied"),
                ],
                max_length=64,
            ),
        ),
    ]
