# Generated by Django 6.0.4 on 2026-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []  # type: ignore[assignment]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("child_identity", "Child identity")], max_length=32
                    ),
                ),
                ("file", models.FileField(upload_to="private/child-identity/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "Not requested"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="not_requested",
                        max_length=32,
                    ),
                ),
                ("uploaded_by_parent_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
