# Generated by Django 6.0.4 on 2026-05-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="registrations.registrationapplication",
            ),
        ),
    ]
