# Generated by Django 6.0.4 on 2026-05-09 04:01

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_private_document_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=apps.documents.storage.PrivateDocumentStorage(),
                upload_to="private/documents/",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("guardian_identity", "Guardian identity"),
                    ("member_identity", "Member identity"),
                    ("member_portrait", "Member portrait"),
                ],
                max_length=32,
            ),
        ),
    ]
