# Generated by Django 6.0.4 on 2026-05-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_file_alter_document_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_error_detail_redacted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_last_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_provider",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="DocumentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                (
                    "extraction_schema_version",
                    models.CharField(blank=True, default="v1", max_length=32),
                ),
                ("encrypted_payload", models.TextField(blank=True, default="")),
                ("encrypted_summary", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
