# Generated by Django 6.0.4 on 2026-09-03 16:48

import apps.documents.models
import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_document_ocr_error_code_and_more"),
        ("members", "0012_memberexporttemplate"),
        ("registrations", "0012_submission_digest_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        storage=apps.documents.storage.PrivateDocumentStorage(),
                        upload_to=apps.documents.models.medical_permit_upload_to,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("parent_upload", "Parent upload"),
                            ("staff_upload", "Staff upload"),
                            ("staff_confirmation", "Staff confirmation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("valid_until", models.DateField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_permit",
                        to="registrations.registrationapplication",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_medical_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_permit",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
