# Generated by Django 6.0.4 on 2026-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_document_ocr_error_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("guardian_identity", "Guardian identity"),
                    ("member_identity", "Member identity"),
                    ("member_identity_back", "Bērna ID kartes aizmugure"),
                    ("member_portrait", "Member portrait"),
                ],
                max_length=32,
            ),
        ),
    ]
