# Generated by Django 6.0.4 on 2026-05-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_magiclinktoken_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("fix_requested", "Fix requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("guardian_full_name", models.CharField(blank=True, max_length=255)),
                ("guardian_personal_id", models.CharField(blank=True, max_length=32)),
                ("guardian_email", models.EmailField(max_length=254)),
                ("guardian_phone", models.CharField(blank=True, max_length=32)),
                ("guardian_address", models.CharField(blank=True, max_length=255)),
                ("child_full_name", models.CharField(blank=True, max_length=255)),
                ("child_personal_id", models.CharField(blank=True, max_length=32)),
                ("child_birth_date", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="accounts.parentaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
