# Generated by Django 6.0.4 on 2026-05-07 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("registrations", "0002_parent_identity_gate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="approved_member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_application",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="review_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Melnraksts"),
                    ("submitted", "Iesniegts"),
                    ("fix_requested", "Jālabo"),
                    ("approved", "Apstiprināts"),
                    ("rejected", "Noraidīts"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
