# Generated by Django 6.0.4 on 2026-05-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_kitsizeoption"),
        ("registrations", "0003_registrationapplication_approved_member_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationapplication",
            name="child_birth_date",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="child_full_name",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="child_personal_id",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_address",
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="field_sources",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="guardian_declared_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_actual_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_kit_size_shirt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shirt_applications",
                to="members.kitsizeoption",
            ),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_kit_size_shorts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shorts_applications",
                to="members.kitsizeoption",
            ),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_personal_id",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="member_same_address_as_guardian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="preferred_agreement_signing",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="support_club_instead_of_multi_child_discount",
            field=models.BooleanField(default=False),
        ),
    ]
