# Generated by Django 6.0.4 on 2026-05-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0004_remove_registrationapplication_child_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationapplication",
            name="preferred_agreement_signing",
            field=models.CharField(
                blank=True,
                choices=[("paper", "Paper"), ("electronic", "Electronic")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="registrationapplication",
            name="support_club_instead_of_multi_child_discount",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
