# Generated by Django 6.0.4 on 2026-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0005_alter_registrationapplication_preferred_agreement_signing_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationapplication",
            name="preferred_agreement_signing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electronic", "Elektroniski"),
                    ("paper", "Ar roku, papīra dokuments"),
                ],
                max_length=16,
            ),
        ),
    ]
