# Generated by Django 6.0.4 on 2026-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0006_alter_registrationapplication_preferred_agreement_signing",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="personal_data_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationapplication",
            name="personal_data_consent_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
