# Generated by Django 6.0.4 on 2026-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0007_personal_data_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="preferred_payment_mode",
            field=models.CharField(
                blank=True,
                choices=[("upfront", "Vienā maksājumā"), ("installments", "Pa daļām")],
                max_length=16,
            ),
        ),
    ]
