# Generated by Django 6.0.4 on 2026-06-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_guardian_parent_account"),
        ("registrations", "0008_registrationapplication_preferred_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="members.guardian",
            ),
        ),
    ]
