# Generated by Django 6.0.4 on 2026-06-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0009_registrationapplication_guardian"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_declared_address",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_email",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_full_name",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_personal_id",
        ),
        migrations.RemoveField(
            model_name="registrationapplication",
            name="guardian_phone",
        ),
    ]
