# Generated by Django 6.0.4 on 2026-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0010_remove_registrationapplication_guardian_declared_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="referral_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
